apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ijpq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ijpq
    app.kubernetes.io/part-of: byoc-app-bkyz
  name: ijpq
spec:
  rules:
  - host: ijpq-byoc-xszc-tenant.apps.e8aa923b283c46410b86.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ijpq
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
